name: ifg_mobile_estudante
description: Aplicativo do Intituto Federal de Goias para os alunos da instituição
publish_to: "none"
version: 1.0.0+1




flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/data/
  fonts:
    - family: Quicksand
      fonts:
        - asset: assets/fonts/Quicksand/Quicksand.ttf

        
dev_dependencies:
  flutter_launcher_icons: "^0.13.1"




environment:
  sdk: ">=3.1.3 <3.19.2"



dependencies:
  url_launcher: ^6.2.4
  http: ^1.2.2
  flutter_secure_storage: ^9.2.2 
  provider: ^6.1.2


  
  flutter:
    sdk: flutter
  flutter_test:
    sdk: flutter

